
version: 2.1


jobs:
  testbcm470x:
    docker:
      - image: paldier/swrt-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build bcm470x
          shell: /bin/bash
          command: |
            git clone --depth=1 https://github.com/SWRT-dev/asuswrt-bcm-ac bcm470x
			if [ ! -d ~/bcm-toolchains ];then
				git clone --depth=1 https://github.com/SWRT-dev/bcm-toolchains ~/bcm-toolchains
			fi
            cd bcm470x/release/src-rt-7.14.114.x/src
            sudo /home/docker/envs/bcm.sh
            make rt-ac5300
  testbcm4908:
    docker:
      - image: paldier/swrt-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build bcm4908
          shell: /bin/bash
          command: |
            git clone --depth=1 https://github.com/SWRT-dev/asuswrt-bcm-ac bcm4908
            cd bcm4908/release/src-rt-5.02hnd
            sudo /home/docker/envs/bcm.sh
            make rt-ac86u

workflows:
  build-workflow:
    jobs:
      - testbcm470x
      - testbcm4908


